### ISSUE TITLE
An error occurred when scale was 3

### ISSUE THREAD

**Issue by Ivan-Zhao** [jmiller656/EDSR-Tensorflow#12]
An error occurred when scale was 3.How to solve it?
  0%|          | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ivanz/workspace/tensor_sr/EDSR-Tensorflow-master/train.py", line 18, in <module>
    network.train(args.iterations,args.savedir)
  File "/home/ivanz/workspace/tensor_sr/EDSR-Tensorflow-master/model.py", line 188, in train
    summary,_ = sess.run([merged,train_op],feed)
  File "/home/ivanz/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/ivanz/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (10, 100, 100, 3) for Tensor u'Placeholder_1:0', which has shape '(?, 99, 99, 3)'

**Comment by jmiller656** [comment]
Hey, sorry about that. I'll be looking at this today. Looks like a small division error on my part

**Comment by lihka1** [comment]
is it solved? .. I am too getting the same error now?...any suggestions for the fixes?

**Comment by jmiller656** [comment]
I've fixed this with my most recent change
