### ISSUE TITLE
error in windows

### ISSUE THREAD

**Issue by 2017develper** [jmiller656/EDSR-Tensorflow#4]
hello i have this error can you help me please and thank you 

Traceback (most recent call last):
  File "test.py", line 31, in <module>
    x,y=data.get_batch(args.numimgs,args.imgsize,down_size)
  File "D:\hala\EDSR-Tensorflow-master\data.py", line 67, in get_batch
    x_img = scipy.misc.imresize(img,(shrunk_size,shrunk_size))
  File "C:\Users\USER\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\scipy\misc\pilutil.py", line 490, in imresize
    imnew = im.resize(size, resample=func[interp])
  File "C:\Users\USER\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\PIL\Image.py", line 1556, in resize
    return self._new(self.im.resize(size, resample))
TypeError: integer argument expected, got float

**Comment by jmiller656** [comment]
Whoops, looks like I made a mistake and forgot to force integer division of image sizes. I've just pushed an update that should fix this. Feel free to re-open this issue if you continue to experience problems
