### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by skdingding** [jmiller656/EDSR-Tensorflow#41]
when i test only one image using your trained model,something wrong at
Predicting...
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    outputs = network.predict(x)
  File "/home/dingyuyang/EDSR-Tensorflow-master/model.py", line 172, in predict
    return self.sess.run(self.out,feed_dict={self.input:x})
  File "/home/dingyuyang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/dingyuyang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (50, 50, 3) for Tensor 'Placeholder:0', which has shape '(?, 50, 50, 3)'
 can you help me?

**Comment by gooodpower** [comment]
you can use: 
inputs = np.expand_dims(inputs, 0) 
outputs = network.predict(inputs)

to make the shape of inputs is [1, h, w, 3]

**Comment by weizhiliang0520** [comment]
add []

**Comment by weizhiliang0520** [comment]
`feed_dict={self.input:x})`
|
|
after--->feed_dict={self.input:[x]})
