### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by yuyifan1991** [jmiller656/EDSR-Tensorflow#44]
Thanks so much for helping me solving the problem which I raised, yesterday, But I have another problem:
2019-03-21 10:31:02.242315: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Done building!
Begin training...
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    network.train(args.iterations,args.savedir)
  File "/home/yuyifan/EDSR-Tensorflow/model.py", line 211, in train
    test_x,test_y = self.test_data(*self.test_args)
  File "/home/yuyifan/EDSR-Tensorflow/data.py", line 67, in get_test_set
    get_image(imgs[0],original_size)
IndexError: list index out of range
 I have check the directory, and it hasn't problem.

**Comment by xinqingbuhao** [comment]
I got the same issue. Howerver, when i use the command " python2 train.py ..." ,the issue can be resolved. But a new issue is i can't use GPU to train.(CUDNN problem,i don't know how to resolve) 
the CPU train :
![Uploading image.png…]()

**Comment by xinqingbuhao** [comment]
![image](https://user-images.githubusercontent.com/37792713/57609179-ee047f00-75a0-11e9-9e9a-9696e44135ba.png)

**Comment by kong1060553768** [comment]
@yuyifan1991   Reduce your SciPy package to 1.21

**Comment by navy63** [comment]
I have the same problem. How can I solve it?

**Comment by navy63** [comment]
The problem  is"'float' object cannot be interpreted as an integer"
			coords_x = x / img_size------→coords_x = x // img_size
			coords_y = y/img_size------→coords_y = y//img_size
	                max_counter = len(train_set)/batch_size------→max_counter = len(train_set)//batch_size
python2 ，

**Comment by FBLeee** [comment]
Solution:   Reduce your SciPy package to 1.2.1

**Comment by FBLeee** [comment]
If you still can't solve it, you can do so, ① first install 【pip install pillow】, ② then 【pip install scipy==1.2.1】
