### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by zengxi77** [jmiller656/EDSR-Tensorflow#49]
I‘v download the pre-trained model files, when I run test.py , I meet this error:
  ( by the way, I put "General-100" in a directory named "data")

Building EDSR...
Done building!
Restoring...
INFO:tensorflow:Restoring parameters from saved_models\model
Restored!
No image argument given
Traceback (most recent call last):

  File "<ipython-input-1-4aaaf972c3b9>", line 1, in <module>
    runfile('C:/Users/Administrator/Desktop/non-local/CODE/EDSR-Tensorflow-master/test.py', wdir='C:/Users/Administrator/Desktop/non-local/CODE/EDSR-Tensorflow-master')

  File "E:\anaconda\envs\python27\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "E:\anaconda\envs\python27\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/Desktop/non-local/CODE/EDSR-Tensorflow-master/test.py", line 28, in <module>
    inputs = x

NameError: name 'x' is not defined

**Comment by 943301098** [comment]
你这个要  这样弄  ：   python test.py --image input.bmp
不要弄地址，【把图片和test.py放在同一个目录下，然后直接运行】，前面不要加地址

**Comment by xiaoyi-st** [comment]
> 你这个要 这样弄 ： python test.py --image input.bmp
> 不要弄地址，【把图片和test.py放在同一个目录下，然后直接运行】，前面不要加地址

我按照您的方法这种弄，发现还是不行，数据加载不进来

**Comment by 943301098** [comment]
> 
> 
> > 你这个要 这样弄 ： python test.py --image input.bmp 
> > 不要弄地址，【把图片和test.py放在同一个目录下，然后直接运行】，前面不要加地址
> 
> 我按照您的方法这种弄，发现还是不行，数据加载不进来

个人建议：去跑EDSR-Pytorch代码，这个tensorflow代码复现结果还是不行！达不到原论文的结果。pytorch就可以

**Comment by xiaoyi-st** [comment]
pytoch代码我也试了，有一些问题我无法解决，您跑过吗？我的电子邮件是xting120@qq.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jmiller656/EDSR-Tensorflow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月27日(星期五) 中午11:27
收件人:&nbsp;"jmiller656/EDSR-Tensorflow"<EDSR-Tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"R"<1120922880@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jmiller656/EDSR-Tensorflow] test error (#49)





   
你这个要 这样弄 ： python test.py --image input.bmp
 不要弄地址，【把图片和test.py放在同一个目录下，然后直接运行】，前面不要加地址
  
我按照您的方法这种弄，发现还是不行，数据加载不进来
  
个人建议：去跑EDSR-Pytorch代码，这个tensorflow代码复现结果还是不行！达不到原论文的结果。pytorch就可以
