### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by naseeresmael** [jmiller656/EDSR-Tensorflow#9]
hi @jmiller656, when i try to trining i found this error

python train.py --dataset F:\EDSR\data\set14

Building EDSR...
2017-09-23 17:28:03.431497: W C:\tf_jenkins\home\workspace\r
ure_guard.cc:45] The TensorFlow library wasn't compiled to u
and could speed up CPU computations.
2017-09-23 17:28:03.431683: W C:\tf_jenkins\home\workspace\r
ure_guard.cc:45] The TensorFlow library wasn't compiled to u
e and could speed up CPU computations.
2017-09-23 17:28:03.738781: I C:\tf_jenkins\home\workspace\r
u\gpu_device.cc:955] Found device 0 with properties:
name: GeForce GTX 650 Ti BOOST
major: 3 minor: 0 memoryClockRate (GHz) 1.0975
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-09-23 17:28:03.738922: I C:\tf_jenkins\home\workspace\r
u\gpu_device.cc:976] DMA: 0
2017-09-23 17:28:03.739364: I C:\tf_jenkins\home\workspace\r
u\gpu_device.cc:986] 0: Y
2017-09-23 17:28:03.739424: I C:\tf_jenkins\home\workspace\r
u\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) ->
0:01:00.0)
Done building!
Begin training...
0%|
Traceback (most recent call last):
File "train.py", line 18, in
network.train(args.iterations,args.savedir)
File "F:\EDSR\model.py", line 212, in train
x,y = self.data(*self.args)
File "F:\EDSR\data.py", line 66, in get_batch
img = crop_center(img,original_size,original_size)
File "F:\EDSR\data.py", line 81, in crop_center
y,x,_ = img.shape
ValueError: not enough values to unpack (expected 3, got 2)

how can i fix that please, sorry for wasting your time.

**Comment by jmiller656** [comment]
Oh, it looks like you are using black and white images. I'll add something in to handle this. For now, if you use RGB images this should still work fine without error

**Comment by naseeresmael** [comment]
you are genius man, you tottly right, i now use only rgb images and the error has gon, but Unfortunately i found new error ...
 python train.py --dataset C:\EDSR\data\set14
Building EDSR...
2017-09-25 21:19:26.452748: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 21:19:26.452991: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-25 21:19:26.944793: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties:
name: GeForce GTX 650 Ti BOOST
major: 3 minor: 0 memoryClockRate (GHz) 1.0975
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
2017-09-25 21:19:26.944981: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0
2017-09-25 21:19:26.945880: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y
2017-09-25 21:19:26.946030: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 650 Ti BOOST, pci bus id: 0000:01:00.0)
Done building!
Begin training...
  0%|                                                                                         | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    network.train(args.iterations,args.savedir)
  File "C:\EDSR\model.py", line 212, in train
    x,y = self.data(*self.args)
  File "C:\EDSR\data.py", line 62, in get_batch
    img_indices = random.sample(range(len(train_set)),batch_size)
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python35\lib\random.py", line 324, in sample
    raise ValueError("Sample larger than population")
ValueError: Sample larger than population

**Comment by jmiller656** [comment]
Usually this error means that the batch size you are using is greater than the number of images that you have to train on. Can you check to see if there are any images in the directory that you passed in as the dataset parameter?

I noticed that last time you entered a directory starting with F:\ and this time it started with C:\

**Comment by naseeresmael** [comment]
again, you are right, now the trining begin without errors, much thank for your help @jmiller656.👍👏🎉
NB : yeah, i make acopy of EDSR progict to C:\ and left the original one in F:\.😊
